### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by roozbehes** [TeaRog/COSC301-Project#1]
- [ ] you should do your analysis in a python notebook file, not a python script. I can not run that script.

- [ ] Please read the milestone requirements again because you are missing all of it and I can not mark it like this.

- [ ] missing method chaining extracted in a python_script.py file

- [ ] missing markdown block for explaining your analysis
